[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
test = "test/unit"
auto_detect_remappings = false
chain_id = 1
auto_detect_solc = true
via_ir = false
optimizer = true
optimizer_runs = 200
libraries = []
extra_output = ["metadata"]
extra_output_files = ["metadata"]
allowed_paths = ["./flatcfm-config.json"]
fs_permissions = [{ access = "read", path = "./flatcfm-config.json"}]

[profile.itest]
test = "test/integration"
via_ir = true

[profile.ftest]
test = "test/fork"
fs_permissions = [{ access = "read", path = "./test/fork"}]

[soldeer]
remappings_generate = true
remappings_regenerate = true
remappings_version = false
remappings_location = "txt"

[dependencies]
"@openzeppelin-contracts" = "5.0.2"
"@realityeth" = { version = "3.0.61", git = "https://github.com/RealityETH/reality-eth-monorepo.git", rev = "c5abe9c19fc6217e9636838e3cf0087e93bb6621" }
forge-std = "1.9.5"
